# Generated by Django 5.0.6 on 2024-06-22 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0003_food_created_at_food_deleted_at_food_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfood",
            unique_together={("user", "name")},
        ),
    ]
